Update README.md
Ebazhanov/in-quiz-questions pull request #413
Opened 2020-09-25 22:51 UTC by monkrus

Add an optional  "Advertise here" table .

2020-09-27 10:36 UTC, Ebazhanov commented on README.md
> +    <th> SEND US A MESSAGE FOR DETAILS!
Again a very good idea @monkrus ! but would recommend you take these responsibilities on your own, so I put your email there!

```suggestion
    <th>SEND US AN <a href = "mailto: sergeisqa@gmail.com">EMAIL </a>FOR DETAILS!
```

2020-09-27 10:37 UTC, Ebazhanov requested changes
Sergey FYI I left some comment, please check it out!

2020-09-30 14:33 UTC, Ebazhanov approved these changes
Thanks go ahead! Approved!!!

2020-09-30 14:47 UTC, monkrus reviewed
Great idea!

2020-09-30 14:47 UTC, merged