Update javascript-quiz.md
Ebazhanov/in-quiz-questions pull request #670
Opened 2020-10-29 21:41 UTC by TaylorOD

- Add - [ ] for each question to make them easier to answer. JavaScript only has one answer it in.
- fix small formatting errors

2020-10-31 17:38 UTC, Ebazhanov requested changes
@TaylorOD thanks for the improvements I added some feedback for your please follow my suggestion and update the rest of the file, then we can merge it. Thank you in advance!

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] !== <<<---Correct
```suggestion
- [x] !==
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] A for statement is generic, but a forEach statement can be used only with an array <<<--Correct
```suggestion
- [x] A for statement is generic, but a forEach statement can be used only with an array
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] x.Y <<<<----Correct
```suggestion
- [x] x.Y
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] undefined the undefined <<<---CORRECT
```suggestion
- [x] undefined the undefined
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] Set <<<---CORRECT
```suggestion
- [x] Set
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [x] an object with a constructor property <<<--- CORRECT
```suggestion
- [x] an object with a constructor property
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] ReferenceError <<<---CORRECT
```suggestion
- [x] ReferenceError 
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] addTax(50); <<<---Correct
```suggestion
- [x] addTax(50);
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] let rate = 100; <<<---Correct
```suggestion
- [x] let rate = 100;
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] var student = new Person(); <<<---Correct
```suggestion
- [x] var student = new Person();
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] `for (var i=1; i<=4; i++) {
```suggestion
- [x] `for (var i=1; i<=4; i++) {
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
>      }` <<<<----Correct
```suggestion
    }`
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] It returns a reference to a variable in its parent scope <<<<---Correct
```suggestion
- [x] It returns a reference to a variable in its parent scope
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] `let discountPrice = function(price) {
```suggestion
- [x] `let discountPrice = function(price) {
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
>      };` <<<<----Correct
```suggestion
    };`
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] 'snow' <<<---Correct
```suggestion
- [x] 'snow'
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] /\d\d:\d\d:\d\d/ <<<---Correct, https://regex101.com/r/6e81up/2
```suggestion
- [x] /\d\d:\d\d:\d\d/ https://regex101.com/r/6e81up/2
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] {desc: "logger"} <<<<---Correct
```suggestion
- [x] {desc: "logger"}
```

2020-10-31 17:38 UTC, Ebazhanov commented on javascript/javascript-quiz.md
> +- [ ] roadTypes[2] <<<---Correct
```suggestion
- [x] roadTypes[2]
```

2020-11-02 18:20 UTC, TaylorOD commented
This should be all set now! Thanks!

2020-11-03 19:00 UTC, Ebazhanov approved these changes
Yes, looks good now! Thank you @TaylorOD :punch:

2020-11-03 19:00 UTC, merged