Update Q20
Ebazhanov/in-quiz-questions pull request #766
Opened 2020-11-15 12:01 UTC by j-j-gajjar

2020-11-16 07:53 UTC, Ebazhanov requested changes

2020-11-16 07:53 UTC, Ebazhanov commented on nosql/nosql-quiz.md
> +    - Use IAM plicy conditions. <<<<----Correct
@j-j-gajjar you might want to update this one as well
```suggestion
    - Use IAM policy conditions. <<<<----Correct
```
thank you in advance!

2020-11-21 12:59 UTC, Ebazhanov approved these changes
Thank you for the improvements @j-j-gajjar, looks very good! :+1:

2020-11-21 12:59 UTC, merged

2020-11-21 13:01 UTC, Ebazhanov commented
@all-contributors please add @j-j-gajjar for design

2020-11-23 03:07 UTC, j-j-gajjar commented
Thank You @Ebazhanov