Update as on 28-12-2020
Ebazhanov/in-quiz-questions pull request #910
Opened 2020-12-28 12:19 UTC by mohsinmsm

2021-01-04 17:35 UTC, Ebazhanov requested changes
@mohsinmsm thanks for PR, left some comments

2021-01-04 17:35 UTC, Ebazhanov commented on java/java-quiz.md
> +```
```suggestion
```java
```

would be great to use java identification, which will highlight code with different color

2021-01-04 17:35 UTC, Ebazhanov commented on java/java-quiz.md
> +```
```suggestion
```java
```

the same here

2021-01-05 06:42 UTC, mohsinmsm commented
@Ebazhanov Kindly review the changes

2021-01-05 13:44 UTC, Ebazhanov approved these changes
Thank you @mohnishkarri, looks perfect now! Approved :punch:

2021-01-05 13:44 UTC, merged

2021-01-05 13:45 UTC, Ebazhanov commented
@all-contributors please add @mohnishkarri for design, code

2021-01-05 13:55 UTC, mohsinmsm commented
> Thank you @mohnishkarri, looks perfect now! Approved 👊

It's @mohsinmsm, I guess there's mistake in name

2021-01-05 13:56 UTC, Ebazhanov commented
oh my bad sorry

2021-01-05 13:57 UTC, Ebazhanov commented
@all-contributors please add @mohsinmsm for design, code